"""
Django settings for CSSA project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"]
DEBUG = (os.environ.get('DEBUG', '') == '1')
ALLOWED_HOSTS = ['*'] if DEBUG else os.environ.get('ALLOWED_HOSTS', '').split()

# Application definition

INSTALLED_APPS = [
    'main.apps.MainConfig',
    'accounts.apps.AccountsConfig',
    'corsheaders',
    'rest_framework',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',  # Security
  "whitenoise.middleware.WhiteNoiseMiddleware",  # Temporary static files server
  'django.contrib.sessions.middleware.SessionMiddleware',  # User session system
  'django.middleware.locale.LocaleMiddleware',  # Localization, datetime format
  'corsheaders.middleware.CorsMiddleware',  # CORS headers
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
  'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
  'django.contrib.messages.middleware.MessageMiddleware',  # One-time messages (required by the administration site)
  'django.contrib.auth.middleware.AuthenticationMiddleware',  # Authentication system
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

REST_FRAMEWORK = {
  # 'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
  # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
  # 'PAGE_SIZE': 10,
  'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
  'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
  'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser'],
}

AUTH_USER_MODEL = "accounts.User"
AUTHENTICATION_BACKENDS = ['accounts.models.AuthBackend']

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en"
TIME_ZONE = 'Europe/London'
USE_I18N = True
USE_TZ = True

# HTML templates
TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'OPTIONS': {
      'context_processors': [
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.messages.context_processors.messages',
        'django.contrib.auth.context_processors.auth',
      ],
    },
    'APP_DIRS': True,
    'DIRS': [
      BASE_DIR / 'templates',  # Global template directories
      BASE_DIR.parent / 'client' / 'build',
    ],
  },
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
  BASE_DIR / 'static',  # Global static file directories
  BASE_DIR.parent / 'client' / 'build' / 'static',
]

STATIC_URL = '/static/'  # Static file web URL
MEDIA_URL = '/media/'  # User-uploaded file web URL
STATIC_ROOT = BASE_DIR / 'static_root'
MEDIA_ROOT = BASE_DIR / 'media_root'

if not DEBUG:
  STORAGES = {
    "staticfiles": {
      "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
      "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
  }


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

if DEBUG:
  CORS_ALLOWED_ORIGINS = ['http://localhost:5173']
  CORS_ALLOW_CREDENTIALS = True
  CSRF_TRUSTED_ORIGINS = ['http://localhost:5173']
  CSRF_COOKIE_SAMESITE = 'None'
  CSRF_COOKIE_SECURE = True  # Ignored locally: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
  SESSION_COOKIE_SAMESITE = 'None'
  SESSION_COOKIE_SECURE = True  # Ignored locally: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
