# Generated by Django 4.2.1 on 2023-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="application_level",
            field=models.IntegerField(
                choices=[
                    (0, "Admin"),
                    (1, "President"),
                    (2, "Committee"),
                    (3, "Member"),
                    (4, "Visitor"),
                ],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="approval_level",
            field=models.IntegerField(
                choices=[
                    (0, "Admin"),
                    (1, "President"),
                    (2, "Committee"),
                    (3, "Member"),
                    (4, "Visitor"),
                ],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.IntegerField(
                choices=[
                    (0, "主席团"),
                    (1, "秘书处"),
                    (2, "财务处"),
                    (3, "事业部"),
                    (4, "媒体部"),
                    (5, "赞助部"),
                    (6, "文艺部"),
                    (7, "文化部"),
                    (8, "外联部"),
                    (9, "体育部"),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
