# Generated by Django 4.2.1 on 2023-06-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_application_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="application_level",
            field=models.IntegerField(
                choices=[(1, "审计"), (2, "主席"), (3, "执委"), (4, "部员"), (5, "访客")],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="approval_level",
            field=models.IntegerField(
                choices=[(1, "审计"), (2, "主席"), (3, "执委"), (4, "部员"), (5, "访客")],
                default=5,
            ),
        ),
    ]
