# Generated by Django 4.2.1 on 2023-06-27 20:51

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[accounts.models.username_validator],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("admin", models.BooleanField(default=False)),
                (
                    "approval_level",
                    models.IntegerField(
                        choices=[(1, "审计"), (2, "主席"), (3, "执委"), (4, "部员"), (5, "访客")],
                        default=5,
                    ),
                ),
                (
                    "application_level",
                    models.IntegerField(
                        choices=[(1, "审计"), (2, "主席"), (3, "执委"), (4, "部员"), (5, "访客")],
                        default=5,
                    ),
                ),
                (
                    "department",
                    models.IntegerField(
                        choices=[
                            (0, "主席团"),
                            (1, "秘书处"),
                            (2, "财务处"),
                            (3, "事业部"),
                            (4, "媒体部"),
                            (5, "赞助部"),
                            (6, "文艺部"),
                            (7, "文化部"),
                            (8, "外联部"),
                            (9, "体育部"),
                            (10, "未分配"),
                        ],
                        default=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to=accounts.models.user_directory_path
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
