# Generated by Django 4.2.1 on 2023-06-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="application_level",
            field=models.IntegerField(
                choices=[(0, "审计"), (1, "主席"), (2, "执委"), (3, "部员"), (4, "访客")],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="approval_level",
            field=models.IntegerField(
                choices=[(0, "审计"), (1, "主席"), (2, "执委"), (3, "部员"), (4, "访客")],
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.IntegerField(
                choices=[
                    (0, "主席团"),
                    (1, "秘书处"),
                    (2, "财务处"),
                    (3, "事业部"),
                    (4, "媒体部"),
                    (5, "赞助部"),
                    (6, "文艺部"),
                    (7, "文化部"),
                    (8, "外联部"),
                    (9, "体育部"),
                    (10, "未分配"),
                ],
                default=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
