# Generated by Django 4.2.1 on 2023-09-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_representative"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
