# Generated by Django 4.2.1 on 2023-11-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_notification_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="budgeteer",
            field=models.BooleanField(default=False),
        ),
    ]
