# Generated by Django 4.2.1 on 2023-06-30 19:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.IntegerField(
                        choices=[
                            (0, "主席团"),
                            (1, "秘书处"),
                            (2, "财务处"),
                            (3, "事业部"),
                            (4, "媒体部"),
                            (5, "赞助部"),
                            (6, "文艺部"),
                            (7, "文化部"),
                            (8, "外联部"),
                            (9, "体育部"),
                            (10, "未分配"),
                        ],
                        default=10,
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[(0, "报销"), (1, "付款"), (2, "预支")], default=0
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sort_code",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=8,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("business", models.BooleanField(default=False)),
                (
                    "currency",
                    models.IntegerField(choices=[(0, "英镑"), (1, "人民币")], default=0),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (-1, "已取消"),
                            (0, "已完成"),
                            (1, "已通过"),
                            (2, "待财务审批"),
                            (3, "待主席审批"),
                            (4, "待部门审批"),
                            (5, "待成员审批"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.IntegerField(
                        choices=[
                            (0, "备注"),
                            (1, "批准"),
                            (2, "驳回"),
                            (3, "创建"),
                            (4, "撤销"),
                            (5, "完成"),
                        ],
                        default=0,
                    ),
                ),
                ("contents", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=main.models.user_directory_path
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sort_code",
                    models.CharField(
                        max_length=6,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=8,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("business", models.BooleanField(default=False)),
                ("public", models.BooleanField(default=True)),
                ("star", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
