# Generated by Django 4.2.1 on 2023-06-28 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="account_number",
            field=models.CharField(
                max_length=8, validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="sort_code",
            field=models.CharField(
                max_length=6, validators=[django.core.validators.MinLengthValidator(6)]
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="contents",
            field=models.TextField(blank=True, null=True),
        ),
    ]
