# Generated by Django 4.2.1 on 2023-06-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_destination_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="level",
            field=models.IntegerField(
                choices=[
                    (-1, "已取消"),
                    (0, "已完成"),
                    (1, "已通过"),
                    (2, "待财务审批"),
                    (3, "待主席审批"),
                    (4, "待部门审批"),
                    (5, "待成员审批"),
                ],
                default=5,
            ),
        ),
    ]
