# Generated by Django 4.2.1 on 2023-08-06 22:05

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_destination_user_alter_event_application_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=main.models.user_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                        ]
                    ),
                    main.models.fileSizeValidator,
                ],
            ),
        ),
    ]
