# Generated by Django 4.2.1 on 2023-06-29 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_application_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="destination",
            old_name="personal",
            new_name="star",
        ),
    ]
