# Generated by Django 4.2.1 on 2023-08-08 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_alter_event_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.IntegerField(
                        choices=[
                            (0, "未分配"),
                            (1, "主席团"),
                            (2, "秘书处"),
                            (3, "财务处"),
                            (4, "事业部"),
                            (5, "媒体部"),
                            (6, "赞助部"),
                            (7, "文艺部"),
                            (8, "文化部"),
                            (9, "外联部"),
                            (10, "体育部"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "currency",
                    models.IntegerField(choices=[(0, "英镑"), (1, "人民币")], default=0),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                (
                    "received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (-1, "已取消"),
                            (0, "已完成"),
                            (1, "待付款"),
                            (2, "待财务审批"),
                            (3, "待主席审批"),
                            (4, "待部门审批"),
                            (5, "待成员审批"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.IntegerField(
                        choices=[
                            (0, "评论"),
                            (1, "批准"),
                            (2, "驳回"),
                            (3, "创建"),
                            (4, "撤销"),
                            (5, "完成"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("contents", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=main.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                ]
                            ),
                            main.models.fileSizeValidator,
                        ],
                    ),
                ),
                (
                    "income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.income"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
