# Generated by Django 4.2.1 on 2023-06-26 16:13

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_event_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=main.models.get_upload_path
            ),
        ),
    ]
