# Generated by Django 4.2.1 on 2023-09-27 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_application_amount_alter_income_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="card_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="platform",
            field=models.IntegerField(
                choices=[(0, "英行"), (1, "中行"), (2, "支付宝"), (3, "微信")], default=0
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="card_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="platform",
            field=models.IntegerField(
                choices=[(0, "英行"), (1, "中行"), (2, "支付宝"), (3, "微信")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="account_number",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="sort_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="account_number",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="sort_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[django.core.validators.MinLengthValidator(6)],
            ),
        ),
    ]
