# Generated by Django 4.2.1 on 2023-11-03 01:11

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0008_application_bank_name_application_card_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="category",
            field=models.IntegerField(
                choices=[(0, "合同"), (1, "活动"), (2, "换汇"), (3, "退款")], default=0
            ),
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.IntegerField(
                        choices=[
                            (0, "未分配"),
                            (1, "主席团"),
                            (2, "秘书处"),
                            (3, "财务处"),
                            (4, "事业部"),
                            (5, "媒体部"),
                            (6, "赞助部"),
                            (7, "文艺部"),
                            (8, "文化部"),
                            (9, "外联部"),
                            (10, "体育部"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (-1, "已取消"),
                            (0, "已完成"),
                            (1, "待付款"),
                            (2, "待财务审批"),
                            (3, "待主席审批"),
                            (4, "待部门审批"),
                            (5, "待成员审批"),
                        ],
                        default=3,
                    ),
                ),
                ("reason", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                ]
                            ),
                            main.models.fileSizeValidator,
                        ],
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("spent", models.IntegerField(default=0)),
                (
                    "spent_actual",
                    models.JSONField(default=main.models.received_json_default),
                ),
                ("profit", models.IntegerField(default=0)),
                ("received", models.IntegerField(default=0)),
                (
                    "received_actual",
                    models.JSONField(default=main.models.received_json_default),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.budget",
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.budget",
            ),
        ),
    ]
