# Generated by Django 4.2.1 on 2023-06-27 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_application_approval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="approval",
            new_name="level",
        ),
    ]
