# Generated by Django 4.2.1 on 2023-11-12 15:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models

def migrate_files(apps, schema_editor):
    files = apps.get_model("main", "file")
    events = apps.get_model("main", "event")
    for event in events.objects.all():
        if event.file:
            file = files.objects.create(
                user=event.user,
                file=event.file,
            )
            event.files.add(file)
            event.save()
    receipts = apps.get_model("main", "receipt")
    for receipt in receipts.objects.all():
        if receipt.file:
            file = files.objects.create(
                user=receipt.user,
                file=receipt.file,
            )
            receipt.files.add(file)
            receipt.save()
    budgets = apps.get_model("main", "budget")
    for budget in budgets.objects.all():
        if budget.file:
            file = files.objects.create(
                user=budget.user,
                file=budget.file,
            )
            budget.plan = file
            budget.save()

class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_income_category_budget_application_budget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=main.models.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                ]
                            ),
                            main.models.fileSizeValidator,
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="budget",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.file",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="files",
            field=models.ManyToManyField(blank=True, to="main.file"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="files",
            field=models.ManyToManyField(blank=True, to="main.file"),
        ),
        migrations.RunPython(
            code=migrate_files,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="budget",
            name="file",
        ),
        migrations.RemoveField(
            model_name="event",
            name="file",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="file",
        ),
    ]
