# Generated by Django 4.2.1 on 2023-11-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_file_budget_plan_event_files_receipt_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="level",
        ),
        migrations.AddField(
            model_name="budget",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.budget"
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.budget"
            ),
        ),
    ]
