# Generated by Django 4.2.1 on 2023-11-24 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_remove_budget_level_budget_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="department",
        ),
        migrations.RemoveField(
            model_name="income",
            name="department",
        ),
    ]
