# Generated by Django 4.2.1 on 2023-06-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="category",
            field=models.IntegerField(choices=[(0, "报销"), (1, "付款"), (2, "预支")]),
        ),
        migrations.AlterField(
            model_name="application",
            name="currency",
            field=models.IntegerField(choices=[(0, "英镑"), (1, "人民币")]),
        ),
        migrations.AlterField(
            model_name="application",
            name="department",
            field=models.IntegerField(
                choices=[
                    (0, "主席团"),
                    (1, "秘书处"),
                    (2, "财务处"),
                    (3, "事业部"),
                    (4, "媒体部"),
                    (5, "赞助部"),
                    (6, "文艺部"),
                    (7, "文化部"),
                    (8, "外联部"),
                    (9, "体育部"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="decision",
            name="action",
            field=models.IntegerField(choices=[(0, "批准"), (1, "拒绝"), (2, "完成")]),
        ),
    ]
