# Generated by Django 4.2.1 on 2023-06-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_application_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="payee",
        ),
        migrations.AddField(
            model_name="application",
            name="account_number",
            field=models.CharField(default="", max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="account_type",
            field=models.CharField(default="", max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="sort_code",
            field=models.CharField(default="", max_length=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Payee",
        ),
    ]
