# Generated by Django 4.2.1 on 2023-06-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_message_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="category",
            field=models.IntegerField(
                choices=[(0, "报销"), (1, "付款"), (2, "预支")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="currency",
            field=models.IntegerField(choices=[(0, "英镑"), (1, "人民币")], default=0),
        ),
        migrations.AlterField(
            model_name="application",
            name="department",
            field=models.IntegerField(
                choices=[
                    (0, "主席团"),
                    (1, "秘书处"),
                    (2, "财务处"),
                    (3, "事业部"),
                    (4, "媒体部"),
                    (5, "赞助部"),
                    (6, "文艺部"),
                    (7, "文化部"),
                    (8, "外联部"),
                    (9, "体育部"),
                    (10, "未分配"),
                ],
                default=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="action",
            field=models.IntegerField(
                choices=[
                    (0, "创建"),
                    (1, "批准"),
                    (2, "待办"),
                    (3, "驳回"),
                    (4, "取消"),
                    (5, "完成"),
                ],
                default=0,
            ),
        ),
    ]
