# Generated by Django 4.2.1 on 2023-06-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_application_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="approval",
            field=models.IntegerField(
                choices=[
                    (-1, "已取消"),
                    (0, "已通过"),
                    (1, "待财务审批"),
                    (2, "待主席审批"),
                    (3, "待部门审批"),
                    (4, "待成员审批"),
                ],
                default=4,
            ),
        ),
    ]
